In [1]:
import torch
from platform import python_version
print(python_version())
print(torch.__version__)
print(torch.cuda.is_available())

3.10.12
2.0.1+cu118
True


In [2]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x, '\n',
      x.shape, '\n',  # размер тензора
      x.dtype, '\n',  # тип
      x.device, '\n',  # где лежит
      x.type(), '\n',  # тип
      x.dim(), '\n',  # размерность
      x.size(), '\n',  # размер; .shape и .size() одно и то же
      x.numel()  # тип тензора
      )

tensor([[1, 2, 3],
        [4, 5, 6]]) 
 torch.Size([2, 3]) 
 torch.int64 
 cpu 
 torch.LongTensor 
 2 
 torch.Size([2, 3]) 
 6


In [3]:
x = torch.cuda.FloatTensor(2, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]], device='cuda:0')


In [4]:
x = torch.IntTensor([1, 2]).float()
print(x, '\n')

x = torch.IntTensor([1, 2]).to(torch.float64)
print(x, '\n')

x = torch.IntTensor([1, 2]) + 0.0
print(x, '\n')

tensor([1., 2.]) 

tensor([1., 2.], dtype=torch.float64) 

tensor([1., 2.]) 



In [5]:
# пустой тензор
x = torch.empty(3, 5)
print(x, '\n')

# тензор из единиц
x = torch.ones(3, 5)
print(x, '\n')

# тензор из 3.14
x = torch.full((3, 5), 3.14, dtype=torch.float)
print(x, '\n')

# единичный тензор (с единицами на главной диагонали)
x = torch.eye(3, 5)
print(x, '\n')

# случайный тензор с элементами, равномерно распределёнными на [0, 1]
torch.manual_seed(123)
x = torch.rand(3, 5)
print(x, '\n')

# случайный тензор с нормально распределёнными элементами
torch.manual_seed(123)
x = torch.randn(3, 5)
print(x, '\n')

# случайный тензор с числами от 2 до 4 (не включая 4)
torch.manual_seed(123)
x = torch.randint(2, 4, (3, 5))
print(x, '\n')

tensor([[-5.3071e-07,  3.1133e-41,  0.0000e+00,  7.0065e-45, -2.5075e+30],
        [ 3.1133e-41, -2.4806e-08,  3.1133e-41,  1.5583e+19,  4.3318e-41],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]) 

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]) 

tensor([[3.1400, 3.1400, 3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400, 3.1400, 3.1400]]) 

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]]) 

tensor([[0.2961, 0.5166, 0.2517, 0.6886, 0.0740],
        [0.8665, 0.1366, 0.1025, 0.1841, 0.7264],
        [0.3153, 0.6871, 0.0756, 0.1966, 0.3164]]) 

tensor([[-0.1115,  0.1204, -0.3696, -0.2404, -1.1969],
        [ 0.2093, -0.9724, -0.7550,  0.3239, -0.1085],
        [ 0.2103, -0.3908,  0.2350,  0.6653,  0.3528]]) 

tensor([[2, 3, 2, 2, 2],
        [2, 2, 3, 3, 2],
        [3, 3, 2, 3, 2]]) 



In [6]:
# аналог np.arange
x = torch.arange(0, 10, 2)
print(x, '\n')

# аналог np.linspace
x = torch.linspace(0, 10, 3)
print(x, '\n')

# аналог np.logspace
x = torch.logspace(0, 1, 3)
print(x, '\n')

# сделать тензоры по образцу (использовать такой же тип и размеры)
print(torch.empty_like(x), '\n')
print(torch.zeros_like(x), '\n')
print(torch.ones_like(x), '\n')

tensor([0, 2, 4, 6, 8]) 

tensor([ 0.,  5., 10.]) 

tensor([ 1.0000,  3.1623, 10.0000]) 

tensor([ 9.4892e+33,  4.3318e-41, -2.5161e+30]) 

tensor([0., 0., 0.]) 

tensor([1., 1., 1.]) 



In [7]:
x = torch.randint(0, 10, (2, 5))

print(x, '\n')
print((x[0], x[0, :], x[[0], :], x[:1, :]), '\n')
print((x[:, [1]], x[:, 1], x[:, -4]), '\n')

print('Это тензор 1x1: ', x[0, 0], '\n')
print('А это уже отдельный элемент: ', x[0, 0].item(), '\n')

tensor([[9, 4, 1, 3, 0],
        [0, 6, 5, 7, 9]]) 

(tensor([9, 4, 1, 3, 0]), tensor([9, 4, 1, 3, 0]), tensor([[9, 4, 1, 3, 0]]), tensor([[9, 4, 1, 3, 0]])) 

(tensor([[4],
        [6]]), tensor([4, 6]), tensor([4, 6])) 

Это тензор 1x1:  tensor(9) 

А это уже отдельный элемент:  9 



In [8]:
a = torch.tensor([[1, 2], [3, 4]])

b = a.new_tensor(a)
b = a.clone().detach()
b = torch.empty_like(a).copy_(a)
b = torch.tensor(a)
b = a.detach().clone()  # лучше копировать так

<ipython-input-8-516b07288ffb>:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than tensor.new_tensor(sourceTensor).
  b = a.new_tensor(a)
<ipython-input-8-516b07288ffb>:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  b = torch.tensor(a)


In [9]:
xt = x.t()
x[0, 0] = 30
print('x: ', x, '\n')
print('xt: ', xt, '\n')

x:  tensor([[30,  4,  1,  3,  0],
        [ 0,  6,  5,  7,  9]]) 

xt:  tensor([[30,  0],
        [ 4,  6],
        [ 1,  5],
        [ 3,  7],
        [ 0,  9]]) 



In [10]:
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[2, 2], [2, 2]])

z = torch.stack((x, y), dim=0)  # состыковка тензоров (по умолчанию dim=0)
print(z, '\n', z.shape)

tensor([[[1, 2],
         [3, 4]],

        [[2, 2],
         [2, 2]]]) 
 torch.Size([2, 2, 2])


In [11]:
x, y = z.unbind(dim=0)  # разстыковка тензоров
print(x, '\n', y)

tensor([[1, 2],
        [3, 4]]) 
 tensor([[2, 2],
        [2, 2]])


In [12]:
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[2, 2], [2, 2]])
print(torch.cat([x, y], axis=1), '\n')
print(torch.cat([x, y], axis=0), '\n')

tensor([[1, 2, 2, 2],
        [3, 4, 2, 2]]) 

tensor([[1, 2],
        [3, 4],
        [2, 2],
        [2, 2]]) 



In [13]:
x = torch.tensor([[1, 2], [3, 4]])
print(x.unsqueeze(dim=0).shape,
      x.unsqueeze(dim=1).shape,
      x.unsqueeze(dim=2).shape)
print(x[None, :, :].shape,
      x[:, None, :].shape,
      x[:, :, None].shape)

torch.Size([1, 2, 2]) torch.Size([2, 1, 2]) torch.Size([2, 2, 1])
torch.Size([1, 2, 2]) torch.Size([2, 1, 2]) torch.Size([2, 2, 1])


In [14]:
# удаление единичных размеров
torch.empty(3, 1, 2, 1).squeeze().shape

torch.Size([3, 2])

In [15]:
h = torch.rand((10000, 10000))

In [16]:
%%time
s = torch.sum(h, axis=1)  # суммы строк быстрее

CPU times: user 36.1 ms, sys: 63 µs, total: 36.2 ms
Wall time: 35.1 ms


In [17]:
%%time
s = torch.sum(h, axis=0)  # суммы столбцов медленнее

CPU times: user 78 ms, sys: 801 µs, total: 78.8 ms
Wall time: 78.7 ms


In [18]:
x = torch.randn(3, 2)
print(x.is_contiguous())
y = torch.transpose(x, 0, 1)
print(y.is_contiguous())
x[0, 0] = 101
print(y[0, 0])

True
False
tensor(101.)


In [19]:
x = torch.arange(4*10*2).view(4, 10, 2)
y = x.permute(2, 0, 1)

print('Смежность:', x.is_contiguous())
print('Вытягиваем:', x.view(-1))

Смежность: True
Вытягиваем: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
        72, 73, 74, 75, 76, 77, 78, 79])


In [20]:
print('Смежность:', y.is_contiguous())
print('Вытягиваем:', y.view(-1))

Смежность: False


RuntimeError: ignored

In [21]:
print('Решейпим:', y.reshape(-1))
print('Делаем смежным и решейпим:', y.contiguous().view(-1))

Решейпим: tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
        36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70,
        72, 74, 76, 78,  1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27,
        29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63,
        65, 67, 69, 71, 73, 75, 77, 79])
Делаем смежным и решейпим: tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
        36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70,
        72, 74, 76, 78,  1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27,
        29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63,
        65, 67, 69, 71, 73, 75, 77, 79])


In [22]:
x = torch.arange(8)
(x.view(4, 2), x.view(2, -1))

(tensor([[0, 1],
         [2, 3],
         [4, 5],
         [6, 7]]),
 tensor([[0, 1, 2, 3],
         [4, 5, 6, 7]]))

In [23]:
print(x, '\n', x.storage(), '\n', x.stride(), '\n', x.t().stride())

tensor([0, 1, 2, 3, 4, 5, 6, 7]) 
  0
 1
 2
 3
 4
 5
 6
 7
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 8] 
 (1,) 
 (1,)


<ipython-input-23-e8e06f1bdb9d>:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  print(x, '\n', x.storage(), '\n', x.stride(), '\n', x.t().stride())


In [24]:
z = torch.rand(1, 2, 3, 4)
z = z.permute(0, 3, 1, 2)  # NxHxWxC -> NxCxHxW
z.shape

torch.Size([1, 4, 2, 3])

In [25]:
x = torch.tensor([[0, 1], [2, 3], [4, 5], [6, 7]])
(x.transpose(0, 1), x.t(), x.t_())  # черта _ означает in-place операцию

(tensor([[0, 2, 4, 6],
         [1, 3, 5, 7]]),
 tensor([[0, 2, 4, 6],
         [1, 3, 5, 7]]),
 tensor([[0, 2, 4, 6],
         [1, 3, 5, 7]]))

In [26]:
x = torch.tensor([[0, 1], [2, 3], [4, 5], [6, 7]])
(x.flatten(), x.view(-1))

(tensor([0, 1, 2, 3, 4, 5, 6, 7]), tensor([0, 1, 2, 3, 4, 5, 6, 7]))

In [27]:
x = torch.tensor([[1, 2], [3, 4]])

# заполнение
x.fill_(3)  # черта _ означает выполнение на данном тензоре
print(x, '\n')
# обнуление
x.zero_()
print(x, '\n')

tensor([[3, 3],
        [3, 3]]) 

tensor([[0, 0],
        [0, 0]]) 

